/* AuditPilot API adapter: the browser renders server state and never owns compliance state. */
(function () {
  const API = window.location.port === '8000' ? '' : 'http://localhost:8000';
  const state = { incident: null, tasks: [], report: null };
  const $ = (id) => document.getElementById(id);
  const json = async (url, options = {}) => {
    const r = await fetch(API + url, { headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options });
    const body = await r.json().catch(() => ({}));
    if (!r.ok) throw new Error(body.detail || `Request failed (${r.status})`);
    return body;
  };
  const show = (view) => {
    document.querySelectorAll('.view').forEach(v => v.classList.toggle('active', v.id === `${view}-view`));
    document.querySelectorAll('.stage-btn').forEach(b => b.classList.toggle('active', b.id === `stage-${view}`));
  };
  const unlock = (stage) => { const e = $(`stage-${stage}`); if (e) e.classList.remove('locked'); };
  const complete = (stage) => { const e = $(`stage-${stage}`); if (e) { e.classList.add('complete'); e.classList.remove('locked'); } };
  const notify = (message, type = 'info') => {
    if (window.App && App.toast) App.toast(message, type); else window.alert(message);
  };
  const form = () => ({
    alert_id: $('f-alert-id').value || `SOC-${Date.now()}`,
    detection_time: new Date($('f-detect-time').value || Date.now()).toISOString(), source: $('f-source').value,
    incident_type: $('f-type').value, severity: document.querySelector('.sev-btn.active')?.dataset.sev || '',
    systems: [...document.querySelectorAll('.systems-grid input:checked')].map(e => e.value), description: $('f-desc').value.trim(),
    financial_exposure: Number($('f-financial').value || 0), customers_impacted: Number($('f-customers').value || 0),
    officer: { name: $('f-officer').value, designation: $('f-desig').value, department: $('f-dept').value,
      email: $('f-email').value, phone: $('f-phone').value }
  });
  const showClassification = (i) => {
    const c = i.classification; $('result-loading').style.display = 'none'; $('result-content').style.display = 'flex';
    $('conf-block').style.display = 'block'; $('conf-pct').textContent = `${Number(c.confidence).toFixed(0)}%`;
    $('conf-fill').style.width = `${c.confidence}%`; $('a1-status').textContent = 'Classification Complete ✓';
    $('result-content').innerHTML = `<div class="verdict-card ${c.reportable ? 'reportable' : 'not-reportable'}"><div class="verdict-label">SERVER RULE ENGINE DECISION</div><div class="verdict-title">${c.reportable ? 'REPORTABLE TO RBI CSITE' : 'NOT REPORTABLE'}</div><p>${c.reasons.join(' ')}</p><small>Rules fired: ${c.rules_fired.join(', ') || 'none'}</small></div>`;
    $('a1-actions').style.display = 'flex'; complete('classification'); unlock('report');
  };
  const renderReport = (r) => {
    $('report-steps').innerHTML = '<div class="report-step done"><div class="rs-dot">✓</div><span>Generated by OpenAI report agent</span></div>';
    $('report-stats').style.display = 'grid'; $('rs-sections').textContent = Object.keys(r.sections).length;
    $('report-act-panel').style.display = 'block'; $('a2-status').textContent = `Report generated (${r.provider}/${r.model})`;
    $('report-doc').innerHTML = `<div class="report-doc-header"><div class="report-doc-title">CYBER SECURITY INCIDENT REPORT</div><div class="report-doc-subtitle">Server-generated RBI CSITE draft · ${r.provider} / ${r.model}</div></div>${Object.entries(r.sections).sort(([a],[b]) => Number(a)-Number(b)).map(([n,s]) => `<div class="report-section"><div class="report-section-title">Section ${n} — ${s.title || ''}</div><pre style="white-space:pre-wrap;font:12px/1.6 Inter;color:#2d3748">${typeof s === 'string' ? s : JSON.stringify(s, null, 2)}</pre></div>`).join('')}`;
    complete('report'); unlock('workbench'); unlock('audit');
  };
  const renderTasks = (payload) => {
    state.tasks = payload.tasks; const cols = { open: [], inprogress: [], closed: [] }; state.tasks.forEach(t => (cols[t.status] || cols.open).push(t));
    ['open', 'inprogress', 'closed'].forEach(s => { const c = $(`col-${s}`); if (!c) return; c.innerHTML = cols[s].map(t => `<div class="task-card" onclick="App.setActiveTask('${t.id}')"><div class="task-card-top"><span class="task-title">${t.title}</span><span class="task-priority-badge ${t.priority}">${t.priority.toUpperCase()}</span></div><div class="task-meta"><span>${t.assignee}</span><span>${t.evidence.length ? `📎 ${t.evidence.length}` : '📎 Evidence required'}</span></div><div class="task-actions"><button class="btn btn-ghost btn-sm" onclick="event.stopPropagation(); App.setActiveTask('${t.id}'); App.uploadEvidence()">Upload evidence</button><button class="btn btn-success btn-sm" onclick="event.stopPropagation(); App.setActiveTask('${t.id}'); App.verifyActiveEvidence()" ${t.evidence.length ? '' : 'disabled'}>Verify latest</button><button class="btn btn-primary btn-sm" onclick="event.stopPropagation(); App.setActiveTask('${t.id}'); App.closeDrawerTask()" ${t.status === 'closed' ? 'disabled' : ''}>Close</button></div></div>`).join(''); $(`cnt-${s}`).textContent = cols[s].length; });
    $('wb-prog-text').textContent = `${state.tasks.filter(t => t.status === 'closed').length} / ${state.tasks.length} tasks`;
  };
  async function submit() {
    try { const p = form(); if (!p.incident_type || !p.severity || !p.description) throw new Error('Incident type, severity, and description are required');
      state.incident = await json('/api/incidents', { method: 'POST', body: JSON.stringify(p) });
      document.body.dataset.incidentId = state.incident.id; $('incident-badge').style.display = 'flex'; $('incident-id-display').textContent = state.incident.incident_id; $('deadline-chip').textContent = 'ACTIVE INCIDENT'; $('deadline-chip').classList.add('live');
      const classified = await json(`/api/incidents/${state.incident.id}/classify`, { method: 'POST' }); state.incident = classified; show('classification'); startDeadlinePolling(); showClassification(classified);
    } catch (e) { notify(e.message, 'error'); }
  }
  async function startReport() { try { show('report'); const r = await json(`/api/incidents/${state.incident.id}/report`, { method: 'POST' }); state.report = r; renderReport(r); } catch (e) { notify(e.message, 'error'); } }
  async function map() { try { show('workbench'); renderTasks(await json(`/api/incidents/${state.incident.id}/tasks`, { method: 'POST' })); complete('workbench'); } catch (e) { notify(e.message, 'error'); } }
  async function uploadEvidence() { const input = document.createElement('input'); input.type = 'file'; input.onchange = async () => { const fd = new FormData(); fd.append('file', input.files[0]); try { const t = state.tasks.find(x => x.id === state.activeTask) || state.tasks[0]; const r = await fetch(`${API}/api/tasks/${t.id}/evidence`, { method: 'POST', body: fd }); if (!r.ok) throw new Error('Evidence upload failed'); renderTasks(await json(`/api/incidents/${state.incident.id}/tasks`)); notify('Evidence uploaded', 'success'); } catch (e) { notify(e.message, 'error'); } }; input.click(); }
  async function verifyActiveEvidence() { try { const t = state.tasks.find(x => x.id === state.activeTask); const e = t && t.evidence[t.evidence.length - 1]; if (!e) throw new Error('Upload evidence before verifying'); await json(`/api/evidence/${e.id}/verify`, { method: 'POST', body: JSON.stringify({ verified: true }) }); renderTasks(await json(`/api/incidents/${state.incident.id}/tasks`)); notify('Evidence verified by server', 'success'); } catch (e) { notify(e.message, 'error'); } }
  async function closeTask() { const t = state.tasks.find(x => x.id === state.activeTask); if (!t) return; try { await json(`/api/tasks/${t.id}`, { method: 'PATCH', body: JSON.stringify({ status: 'closed' }) }); renderTasks(await json(`/api/incidents/${state.incident.id}/tasks`)); notify('Task closed with server-verified evidence', 'success'); } catch (e) { notify(e.message, 'error'); } }
  async function startDeadlinePolling() { const tick = async () => { if (!state.incident) return; try { const d = await json(`/api/incidents/${state.incident.id}/deadlines`); const rem = d.deadlines.full_report.remaining_seconds * 1000; const text = `${String(Math.floor(rem / 3600000)).padStart(2,'0')}:${String(Math.floor(rem / 60000) % 60).padStart(2,'0')}:${String(Math.floor(rem / 1000) % 60).padStart(2,'0')}`; ['timer-full','timer-certin','wb-t1','wb-t2'].forEach(id => { if ($(id)) $(id).textContent = rem > 0 ? text : 'BREACHED'; }); } catch (_) {} }; tick(); setInterval(tick, 1000); }
  async function audit() { if (!state.incident) return; try { const a = await json(`/api/incidents/${state.incident.id}/audit`); const body = $('audit-tbody'); body.innerHTML = a.events.map(e => `<tr><td>#${e.id}</td><td>${new Date(e.timestamp).toLocaleString()}</td><td>${e.stage}</td><td>${e.actor}</td><td>${e.actor_type}</td><td>${e.action}</td><td>${e.status}</td></tr>`).join(''); } catch (e) { notify(e.message, 'error'); } }
  const oldNav = App.nav; App.submit = submit; App.startReport = startReport; App.convertToMAP = map; App.uploadEvidence = uploadEvidence; App.verifyActiveEvidence = verifyActiveEvidence; App.closeDrawerTask = closeTask; App.setActiveTask = id => { state.activeTask = id; }; App.fillDemo = () => notify('Demo data is disabled. Enter a real SOC alert payload.', 'info'); App.nav = view => { if (view === 'audit') audit(); show(view); };
  document.addEventListener('DOMContentLoaded', () => { $('f-alert-id').value = ''; $('f-detect-time').value = new Date().toISOString().slice(0,16); });
})();
